UI/Controllers/BookTouricoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common.hotelflowSvc;
using Common.hotelflowReservationSvc;
using System.Text.RegularExpressions;
using System.Globalization;

namespace UI.Controllers
{
    public class BookTouricoController : Controller
    {
        //
        // GET: /BookTourico/

        public ActionResult Index(FormCollection collection)
        {

           return View();
        }

        public ActionResult SearchTourico()
        {
            //AuthHeader
            Common.hotelflowSvc.AuthenticationHeader auth = new AuthenticationHeader();
            auth.LoginName = "Tra105";
            auth.Password = "111111";

            FormCollection collection = TempData["col"] as FormCollection;

            //SearchHotelRequest
            Common.hotelflowSvc.SearchRequest reqCriteria = new SearchRequest();
            reqCriteria.CheckIn = Convert.ToDateTime(collection["checkIn"]);
            reqCriteria.CheckOut = Convert.ToDateTime(collection["checkOut"]);
            reqCriteria.Destination = "YTO";// collection["add"];

            
            reqCriteria.RoomsInformation = new RoomInfo[] {
                                                                new RoomInfo {
                                                                               AdultNum = Convert.ToInt16(collection["ddlTotalGuest"]),
                                                                               ChildAges =  new ChildAge[] { new ChildAge { age = 5 } },
                                                                               ChildNum  = 1
                                                                }};

            HotelFlowClient client = new HotelFlowClient();
            SearchResult sreq = client.SearchHotels(auth, reqCriteria, new Feature[] { new Feature { name = "OriginalImageSize", value = "true" } });

          

            ViewBag.StartDate = reqCriteria.CheckIn;
            ViewBag.EndDate = reqCriteria.CheckOut;
            ViewBag.Adults = Convert.ToInt16(collection["ddlTotalGuest"]);

            ViewBag.Lat = double.Parse(collection["lat"]);
            ViewBag.Lan = double.Parse(collection["lan"]);


            return View("SearchHotel", sreq.HotelList);
        }

        //NOTE: skipped using this method in POC - GetHotelDetailsV3 could be combined with CheckAvailabilityAndPrices to show more details
        public ActionResult GetHotelInfo(FormCollection collection)
        {
            //AuthHeader
            Common.hotelflowSvc.AuthenticationHeader auth = new AuthenticationHeader();
            auth.LoginName = "Tra105";
            auth.Password = "111111";

            var hotelIds = new HotelID[] { new HotelID { id =  Convert.ToInt32(collection["hotelCode"]) } };
          
            HotelFlowClient client = new HotelFlowClient();
            TWS_HotelDetailsV3 sreq = client.GetHotelDetailsV3(auth, hotelIds, new Feature[] { new Feature { name = "OriginalImageSize", value = "true" } });
            client.Close();

            ViewBag.StartDate = collection["startDate"];
            ViewBag.EndDate = collection["endDate"];

            //return View("HotelInfo", sreq);         
            return View("HotelDisplay", sreq);

        }


        // public ActionResult CheckAvailability(int hotelId)
        public ActionResult CheckAvailability(FormCollection collection)
        {
            //AuthHeader
            Common.hotelflowSvc.AuthenticationHeader auth = new AuthenticationHeader();
            auth.LoginName = "Tra105";
            auth.Password = "111111";

            //SearchHotelRequest
            Common.hotelflowSvc.SearchHotelsByIdRequest reqCriteria = new SearchHotelsByIdRequest();
            reqCriteria.HotelIdsInfo = new HotelIdInfo[] {
                                                    new HotelIdInfo { id = Convert.ToInt32(collection["hotelCode"]) }
            };

            reqCriteria.CheckIn =  Convert.ToDateTime(collection["startDate"]);
            reqCriteria.CheckOut = Convert.ToDateTime(collection["endDate"]);

            ViewBag.StartDate = reqCriteria.CheckIn;
            ViewBag.EndDate = reqCriteria.CheckOut;

            reqCriteria.RoomsInformation = new RoomInfo[] {
                                                                new RoomInfo {
                                                                               AdultNum = 1,
                                                                               ChildAges =  new ChildAge[] { new ChildAge { age = 5 } },
                                                                               ChildNum  = 1
                                                                }};

            HotelFlowClient client = new HotelFlowClient();
            SearchResult sreq = client.CheckAvailabilityAndPrices(auth, reqCriteria, new Feature[] { new Feature { name = "OriginalImageSize", value = "true" } });
            client.Close();
           
            
            //sreq.HotelList[0].RoomTypes[0].Occupancies[0]
            
            return View("Available", sreq.HotelList);

        }


        // public ActionResult BookHotel(int hotelId,int hotelroomTypeId, Decimal occPubPrice)
        public ActionResult BookHotel(FormCollection collection)
        {
            //AuthHeader
            Common.hotelflowSvc.AuthenticationHeader auth = new AuthenticationHeader();
            auth.LoginName = "Tra105";
            auth.Password = "111111";

            //SearchHotelRequest
            Common.hotelflowSvc.BookV3Request reqCriteria = new BookV3Request();
            reqCriteria.RecordLocatorId = 0;
            reqCriteria.HotelId = Convert.ToInt32(collection["hotelCode"]); 
            reqCriteria.HotelRoomTypeId = Convert.ToInt32(collection["hotelroomTypeId"]);

            reqCriteria.CheckIn = Convert.ToDateTime(collection["startDate"]);
            reqCriteria.CheckOut = Convert.ToDateTime(collection["endDate"]);

            reqCriteria.RoomsInfo = new RoomReserveInfo[]
            {
                new RoomReserveInfo {  AdultNum = 1,
                                       ChildAges =  new ChildAge[] { new ChildAge { age = 5 } },
                                       ChildNum  = 1 ,
                                       ContactPassenger = new ContactPassenger { FirstName = "Jack", LastName = "Rowling" }
                                    }
            };

            reqCriteria.Currency = "CAD";             
            reqCriteria.PaymentType = PaymentTypes.Obligo;
            reqCriteria.RequestedPrice = Convert.ToDecimal(collection["occPubPrice"]);

            ViewBag.HotelId = reqCriteria.HotelId;
            ViewBag.HotelRoomTypeId = reqCriteria.HotelRoomTypeId;

            HotelFlowClient client = new HotelFlowClient();

            RGInfoResults sreq;

            try
            {

                ////Cancellation Policies
                //HotelPolicyType1 cancelresp = client.GetCancellationPolicies(AuthenticationHeader: auth, nResId: 0, hotelId: 16455, hotelRoomTypeId: 14411, productId: 0, dtCheckIn: Convert.ToDateTime("2016-05-25"), dtCheckOut: Convert.ToDateTime("2016 - 05 - 28"));
                //RoomTypePolicyType1 pol = cancelresp.RoomTypePolicy;
                //pol.CancelPolicy[].PenaltyDescription;
                //client.Close();
                //CostAmendRequest k = new CostAmendRequest;
                //AmendRequest r = new AmendRequest();

                //ReservationsServiceSoapClient clnt = new ReservationsServiceSoapClient();
                
                
                sreq = client.BookHotelV3(AuthenticationHeader: auth,request: reqCriteria, features: new Feature[] { new Feature { name = "OriginalImageSize", value = "true" } });
                
            }
            catch (System.ServiceModel.FaultException ex)
            {
                return View("PriceChange", ex);                   
            }
            finally
            {
                client.Close();
            }

            return View("Confirmation", sreq.ResGroup);

            

        }

        public static Decimal ExtractDecimalFromString(string str)
        {

            Regex digits = new Regex(@"^\D*?((-?(\d+(\.\d+)?))|(-?\.\d+)).*");
            Match mx = digits.Match(str);
            //Console.WriteLine("Input {0} - Digits {1} {2}", str, mx.Success, mx.Groups);

            return mx.Success ? Convert.ToDecimal(mx.Groups[1].Value) : 0;
        }

        public ActionResult BookHotelFinal(FormCollection collection)
        {
            //AuthHeader
            Common.hotelflowSvc.AuthenticationHeader auth = new AuthenticationHeader();
            auth.LoginName = "Tra105";
            auth.Password = "111111";

            //SearchHotelRequest
            Common.hotelflowSvc.BookV3Request reqCriteria = new BookV3Request();
            reqCriteria.RecordLocatorId = 0;
            reqCriteria.HotelId = Convert.ToInt32(collection["hotelCode"]);
            reqCriteria.HotelRoomTypeId = Convert.ToInt32(collection["hotelroomTypeId"]);

            reqCriteria.CheckIn = Convert.ToDateTime("2016-04-22"); // Convert.ToDateTime(collection["checkIn"]);
            reqCriteria.CheckOut = Convert.ToDateTime("2016-04-24");//Convert.ToDateTime(collection["checkOut"]);


            reqCriteria.RoomsInfo = new RoomReserveInfo[]
            {
                new RoomReserveInfo {  AdultNum = 1,
                                       ChildAges =  new ChildAge[] { new ChildAge { age = 5 } },
                                       ChildNum  = 1 ,
                                       ContactPassenger = new ContactPassenger { FirstName = "Jack", LastName = "Rowling" }
                                    }
            };

            reqCriteria.Currency = "CAD";
            reqCriteria.PaymentType = PaymentTypes.Obligo;
                   

UI/Controllers/PriceBreakupController.cs
using Common;
using Common.Sabre.Hotels.RateDetails;
using Manager;
using Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class PriceBreakupController : Controller
    {
        //
        // GET: /PriceBreakup/
        [Authorize]
        public ActionResult Index(FormCollection collection)
        {
            HotelRateDescriptionRS priceBreakup = null;
            HotelSelectDto select = new HotelSelectDto();
            select.StartDate = Request.QueryString["startDate"];
            select.EndDate = Request.QueryString["endDate"];
            select.TotalTravellers = Request.QueryString["totalTravellers"];
            select.HotelCode = Request.QueryString["hotelCode"];
            select.RPHNumber = Request.QueryString["propertyRphNumber"];

            var session = SabreSessionManager.Create();
            select.SessionId = session.SecurityValue.BinarySecurityToken;
            var hotelDesc = new HotelPropertyDescription()
               .HotelDescription(select);

            //Get pricing information
            if (hotelDesc.RoomStay != null && hotelDesc.RoomStay.RoomRates != null)
            {
                HotelPricing pricing = new HotelPricing();
                select.RPHNumber = select.RPHNumber;
                priceBreakup = pricing.GetPricing(select);  
            }

            SessionClose closeSession = new SessionClose();
            closeSession.Close(select.SessionId);

            return View(priceBreakup);
        }

    }
}

UI/Views/BookTourico/Available.cshtml
@model Common.hotelflowSvc.Hotel[]
@{
    ViewBag.Title = "Tourico Hotel Search Result";
}
<h1>Tourico Hotel Search Result</h1>

 <div style="background-color:white; padding:10px; margin:10px; font-size:12px;">

     <script src="~/Scripts/jquery-1.8.2.js"></script>
     <script src="~/Scripts/jquery-ui-1.8.24.js"></script>
     
     <table>
            @foreach (Common.hotelflowSvc.Hotel t in Model)
            {
                <tr>
                    <td>
                        <h1>@t.name</h1>
                    </td>
                    <td>
                        <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                    </td>
                    <td align="left"><b>Min.Avg Price:</b>@t.minAverPublishPrice</td>
                </tr>

                <tr>
                    <td colspan="2">
                        @{
                            @t.Location.address
                        }
                    </td>
                    <td align="left"><b>Category: </b>@t.category</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div>
                            @* <span class="glyphicon glyphicon-phone-alt" aria-hidden="true" style="font-size:20px;"></span>*@
                            @t.desc
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                </tr>
                <tr>
                    <td>
                        <img src=@t.thumb />
                    </td>
                </tr>

                <tr>
                    <td colspan="3">
                        <b><u>Available Rooms: @t.NumOfRoom</u></b>
                    </td>
                </tr>

                <tr>
                    @*<td><b>RoomType Id</b></td>*@
                    <td><b>Type</b></td>
                    <td><b>Room Category</b></td>
                    <td><b>Room No.</b></td>
                    <td><b>Availability</b></td>
                    <td><b>Price</b></td>
                </tr>

                            foreach (Common.hotelflowSvc.RoomType r in t.RoomTypes)
                            {
                                <tr>
                                    @using (Html.BeginForm("BookHotel", "BookTourico"))
                                {
                                        @*<td>
                                            <a href="#" class="dialog-trigger">@r.hotelRoomTypeId</a>
                                            <div id="client-detail-modal">
                                                @Html.Partial("popupRoomInfo",Model )
                                            </div>
                                        </td>*@
                                        <td>@r.name </td>
                                        <td>@r.roomTypeCategory </td>
                                        <td>@r.roomId</td>
                                        <td>@(r.isAvailable ? "Yes" : "No")</td>
                                        <td>@r.Occupancies[0].occupPublishPrice</td>
                                        <td>
                                            <input type="hidden" name="startDate" value="@ViewBag.StartDate" />
                                            <input type="hidden" name="endDate" value="@ViewBag.EndDate" />
                                            <input type="hidden" name="hotelCode" value="@t.hotelId" />
                                            <input type="hidden" name="hotelroomTypeId" value="@r.hotelRoomTypeId" />
                                            <input type="hidden" name="occPubPrice" value="@r.Occupancies[0].occupPublishPrice" />
                                            <button type="submit" class="btn btn-warning" style="width:150px;">Book</button>
                                        </td>
                                    }
                                </tr>
                                }
                            }
        </table>

    </div>

UI/Views/BookTourico/Confirmation.cshtml
@model Common.hotelflowSvc.ResGroup

@{
    ViewBag.Title = "Hotel Booking - Tourico Confirmation";
}
<h1>Your booking was successful - Tourico </h1>

<br />

<h1>Thank you for your booking, you will receive an email confirming your booking.</h1>

<br />

<h1>Your Transaction number  @Model.tranNum</h1>

UI/Views/BookTourico/HotelDisplay.cshtml
@model Common.hotelflowSvc.TWS_HotelDetailsV3
@{
    ViewBag.Title = "Index";
}

<h2>Hotel Property Details - Tourico</h2>
<div style="background-color:white; padding:10px; margin:10px; font-size:12px;">
    @if (true)
    {
        <table>
            <tr>
                <td>
                    <h1>@Model.Hotel[0].name</h1>
                </td>
                <td>
                    <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                    <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                    <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                    <span class="glyphicon glyphicon-star" aria-hidden="true" style="color:orange; font-size:20px;"></span>
                </td>
                <td align="right"><b>Check-In Time: </b>@ViewBag.StartDate</td>
            </tr>
            <tr>
                <td colspan="2">

                    @{

                        if (Model.Location.Rows.Count > 0)
                        {                            
                            var hotelAddress = string.Empty;
                            try
                            {
                                if (Model.Location[0].location != null)
                                {
                                    hotelAddress += Model.Location[0].location + ", ";
                                }
                                hotelAddress += Model.Location[0].destinationCode;
                            }
                            catch { };
                            @hotelAddress

                        }
                    }
                   
                </td>
                <td align="right"><b>Check-Out Time: </b>@ViewBag.EndDate</td>
            </tr>
            <tr>
                <td colspan="2">
                    <div>
                        <span class="glyphicon glyphicon-phone-alt" aria-hidden="true" style="font-size:20px;"></span>
                        @Model.Hotel[0].hotelPhone  , @Model.Hotel[0].hotelFax
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">      

                </td>
            </tr>
        </table>
        <table width="100%">
            <tr>
                <td></td>
                <td><b><u>Options Info:</u></b></td>
                <td><b><u>Property Type:</u></b></td>
            </tr>
            <tr>
                <td>
                    <img src=@Model.Hotel[0].thumb />
                </td>
                <td>
                    <div style="overflow:auto; max-height:250px; max-width:300px;">
                        @{
                            @*foreach (var t in Model.RoomStay.BasicPropertyInfo.PropertyOptionInfo.GetType().GetProperties())
                            {
                                var value = t.GetValue(Model.RoomStay.BasicPropertyInfo.PropertyOptionInfo, null);
                                <b>@t.Name: </b><span>True/False</span><br />
                            }*@
                        }
                    </div>
                </td>
                <td>
                    <div style="overflow:auto; max-height:250px; max-width:300px;">
                        @{
                            @*foreach (var t in Model.RoomStay.BasicPropertyInfo.PropertyTypeInfo.GetType().GetProperties())
                            {
                                var value = t.GetValue(Model.RoomStay.BasicPropertyInfo.PropertyTypeInfo, null);
                                <b>@t.Name: </b><span>True/False</span><br />
                            }*@
                        }
                    </div>
                </td>
            </tr> 
           
            <tr>
               
            </tr>  
           <tr>
                <td colspan="3">
                    <b><u>Available Rooms</u></b>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    @if (true)
                    {
                        <table width="100%">
                       <tr>
                           <th width="40%">Room Types</th>
                           <th>Room Code</th>
                           <th></th>
                           <th>Type</th>
                       </tr>
                       <tr>
                           <td colspan="4"><hr /></td>
                       </tr>
                       @{
                           foreach (var roomtype in @Model.RoomType)
                           {
                               if(true)
                               {
                               <tr>                                   
                                   <td>   
                                       @*@{ var name = string.Empty; int counter = 0; }                                 
                                        @foreach(var desc in rate.AdditionalInfo.Text){
                                            if (counter == 0)
                                            {*@ 
                                                <p><b>@roomtype.name</b></p>
                                                @*counter += 1;*@
                                            @*}  
                                            else
                                            {
                                                <span style="font-size:10px;">@desc</span>
                                            }        
                                        }
                                       @name*@                                               
                                   </td>
                                   <td>
                                       @roomtype.roomId
                                   </td>
                                   <td>
                                       
                                       @*@{ 
                                           var totalAmount = string.Empty;
                                           foreach(var rte in rate.Rates)
                                           {
                                               totalAmount = rte.CurrencyCode + " " + rte.Amount;
                                           }
                                        }
                                       @using (Html.BeginForm("Index", ""))
                                       {
                                        @Html.ActionLink(totalAmount, "Index", "PriceBreakup", new { @startDate = @Model.RoomStay.TimeSpan.Start,
                                                                                                     @endDate = @Model.RoomStay.TimeSpan.End,
                                                                                                     @totalTravellers = @ViewBag.TotalTravellers,
                                                                                                     @hotelCode = @Model.RoomStay.BasicPropertyInfo.HotelCode,
                                                                                                     @propertyRphNumber = @rate.RPH}, null) 
                                       }*@
                                       
                                   </td>
                                   <td>
                                       @roomtype.roomTypeCategory
                                   </td>
                                   <td>
                                       @using (Html.BeginForm("CheckAvailability", "BookTourico"))
                                       {
                                        <input type="hidden" name="startDate" value="@ViewBag.StartDate" />
                                        <input type="hidden" name="endDate" value="@ViewBag.EndDate" />
                                        <input type="hidden" name="totalTravellers" value="@ViewBag.TotalTravellers" />
                                        <input type="hidden" name="hotelCode" value="@Model.Hotel[0].hotelID"/>
                                        <input type="hidden" name="hotelRoomId" value="@roomtype.GetHotelRoomTypeIdsRows()[0].HotelRoomTypeIds_Id" />
                                        <input type="hidden" name="propertyRphNumber" value="" />
                                           <button type="submit" class="btn btn-success">Check Availability</button>
                                       }
                                   </td>
                               </tr>
                                <tr><td>&nbsp;</td></tr>
                                <tr>
                                    <td colspan="4" valign="baseline">
                                     @*   <b>CancelPolicy:</b> Cancellation should be made  @rate.AdditionalInfo.CancelPolicy.Numeric @rate.AdditionalInfo.CancelPolicy.Option before check-In date.*@
                                    </td>
                                </tr>
                               <tr>
                                 <td colspan="4"><hr /></td>
                               </tr>
                               }
                           }                           
                       }
                    
                   </table>
                    }
                    else
                    {
                        <p style="color:red; font-size:15px;">No room available</p>
                    }
                </td>
            </tr>  

        </table>
    }
    else
    {
        <h1><p style="color:red;">No record found.</p></h1>
    }



</div>

UI/Views/BookTourico/HotelInfo.cshtml
@model Common.hotelflowSvc.TWS_HotelDetailsV3
@{
    ViewBag.Title = "Tourico Hotel Info";
}
<h1>Tourico Hotel Search Result</h1>



<table>
    <thead>
        <tr>
            
        </tr>
    </thead>
    <tbody> 

        <tr>
            <td><b>Hotel Id</b></td>
            <td><b>Rooms</b></td>
            <td><b>Currency</b></td>
            <td><b>Thumb</b></td>
            <td><b>Phone</b></td>
        </tr>
             
            @foreach (System.Data.DataRow dr in Model.Tables["Hotel"].Rows)
            {                
            <tr>
                <td>@Html.ActionLink(dr[0].ToString(), "CheckAvailability", new { hotelId = Convert.ToInt32(dr[0].ToString()) })</td>    
                <td>@dr["rooms"].ToString()</td>    
                <td>@dr["currency"].ToString()</td>    
                <td> <img  src=@dr["thumb"].ToString() /></td>    
                <td>@dr["hotelphone"].ToString()</td>       
            </tr>          
           }

        <tr>
            <td><b>Description: </b></td>
        </tr>
        @foreach (System.Data.DataRow dr in Model.Tables["LongDescription"].Rows)
        {
            <tr>
                <td>@dr[0].ToString()</td>               
            </tr>
        }

        <tr>
            <td><b>Room No.</b></td>
            <td><b>Name</b></td>
            <td><b>Room Category</b></td>          
        </tr>
        
        @foreach (System.Data.DataRow dr in Model.Tables["RoomType"].Rows)
        {
            <tr>
                <td>@dr["roomId"].ToString()</td>
                <td>@dr["name"].ToString()</td>
                <td>@dr["roomTypeCategory"].ToString()</td>               
            </tr>
        }


    </tbody>
</table>

UI/Views/BookTourico/PriceChange.cshtml
@model System.ServiceModel.FaultException

@{
    ViewBag.Title = "Hotel Booking - Price Change";
}
<h1>Your booking Status</h1>

<br />

<br />

<h1>@Model.Message</h1>

<h1>Do You Want to Book with New Price?</h1>

<table>
<tr>
<td>    
   
</td>
<td>
@using (Html.BeginForm("BookHotelFinal", "BookTourico"))
{
    <input type="hidden" name="hotelCode" value="@ViewBag.HotelId" />
    <input type="hidden" name="hotelroomTypeId" value="@ViewBag.HotelRoomTypeId" />
    <input type="hidden" name="message" value="@Model.Message" />
    <button type="submit" class="btn btn-warning" style="width:150px;">Yes</button>
    <button type="button" class="btn btn-warning" style="width:150px;" onclick="history.back()">Back</button>
 }
</td>
</tr>
</table>

UI/Views/BookTourico/Tourico.cshtml
@model List<Common.hotelflowSvc.Hotel>
@{
    ViewBag.Title = "Tourico Hotel Search Result";
}
<h1>Tourico Hotel Search Result</h1>

<table>
    <thead>
        <tr>
            1
        </tr>
    </thead>
    <tbody>

        @foreach (var t in Model)
            {
            <tr>
                <td>@Html.ActionLink(@t.hotelId.ToString(), "BookHotel", "BookTourico", new { hotelId = @t.hotelId }, null)</td>
                <td>@t.name</td>
                <td>@t.NumOfRoom </td>
                <td>@t.minAverPrice </td>
                <td>@t.category </td>
            </tr>
        }

        <tr>
            <td>
                <input type="hidden" name="startDate" value="@ViewBag.StartDate" />
                <input type="hidden" name="endDate" value="@ViewBag.EndDate" />
                <input type="hidden" name="adults" value="@ViewBag.Adults" />
            </td>
        </tr>

    </tbody>
</table>

UI/Views/BookTourico/popupRoomInfo.cshtml
@model Common.hotelflowSvc.Hotel[]
<h2>Room Details</h2>