UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Common.Sabre.Hotels.Search;
using Manager;
using Repository;
using System.Runtime.Caching;
using Common.hotelflowSvc;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        private static MemoryCache _cache = new MemoryCache("ExampleCache");

        [Authorize]
        public ActionResult Index()
        {
            //ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult BookHotel(FormCollection collection)
        { 
            return View();
        }

        [Authorize]
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Tourico")]
        public ActionResult SearchTourico(FormCollection collection)
        {
            TempData["col"] = collection;
      
            return RedirectToAction("SearchTourico","BookTourico",collection);                                            

        }

        [Authorize]
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Sabre")]
        public ActionResult SearchSabre(FormCollection collection)
        {
            HotelSearchDto searchCriteria = new HotelSearchDto();
            searchCriteria.Address = collection["add"];
            searchCriteria.Latitude = double.Parse(collection["lat"]);
            searchCriteria.Longitude = double.Parse(collection["lan"]);
            searchCriteria.StartDate = collection["checkIn"];
            searchCriteria.EndDate = collection["checkOut"];
            searchCriteria.TotalGuest = collection["ddlTotalGuest"];
            searchCriteria.TotalRoom = collection["ddlNoOfRooms"];
            //Check in cache
            var key = searchCriteria.Latitude.ToString() + searchCriteria.Longitude.ToString() + searchCriteria.StartDate.ToString() + searchCriteria.EndDate.ToString();
            var result = GetFromCache(key);
            if (result == null)
            {
                SearchHotel mgr = new SearchHotel();
                result = mgr.Search(searchCriteria);
                AddToCache(result, key);
            }
            ViewBag.StartDate = searchCriteria.StartDate;
            ViewBag.EndDate = searchCriteria.EndDate;
            ViewBag.TotalTravellers = searchCriteria.TotalGuest;
            ViewBag.Lat = searchCriteria.Latitude;
            ViewBag.Lan = searchCriteria.Longitude;
            return View(result);
        }

        private void AddToCache(object value, string key)
        {
            _cache.Set(key, value, new CacheItemPolicy());
        }

        private object GetFromCache(string key)
        {
            var item = _cache.Get(key);
            return item;
        }
    }
}

UI/Controllers/HotelDetailsController.cs
using Common;
using Manager;
using Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class HotelDetailsController : Controller
    {
        //
        // GET: /HotelDetails/
        [Authorize]
        public ActionResult Index(FormCollection collection)
        {
            HotelSelectDto select = new HotelSelectDto();
            select.StartDate = collection["startDate"];
            select.EndDate = collection["endDate"];
            select.TotalTravellers = collection["totalTravellers"];
            select.HotelCode = collection["hotelCode"];

            var session = SabreSessionManager.Create();
            select.SessionId = session.SecurityValue.BinarySecurityToken;
            var hotelDesc = new HotelPropertyDescription()
               .HotelDescription(select);

            ViewBag.TotalTravellers = select.TotalTravellers;

            SessionClose closeSession = new SessionClose();
            closeSession.Close(select.SessionId);
            return View(hotelDesc);
        }

    }
}

UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Hotel Search";
}

@section featured {
   @* @using (Html.BeginForm("SearchHotel", "Home"))*@
    @using (Html.BeginForm())
    {
        <section class="featured" style="font-size:12px;">

            <div class="content-wrapper">
                <table style="width:100%">
                    <tr>
                        <td>
                            <hgroup style="font-size:20px;">
                                <h2>Book Domestic & International Hotels</h2>
                            </hgroup>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>
                                Find best deals across million of hotels across globe
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group">
                                <label for="place-input">Address</label>
                                @*<select id="ddlLocation" name="ddlLocation" style="height:50px; font-size:18px;width:715px;">
                                        <option value="DFW">Dallas Fort Worth International</option>
                                        <option value="ATL">Hartsfield Jackson Atlanta International</option>
                                        <option value="ORD">Chicago O'Hare International</option>
                                        <option value="LAX">Los Angeles International</option>
                                        <option value="SFO">San Francisco International</option>
                                        <option value="LAS">Las Vegas</option>
                                        <option value="IAH">Houston</option>
                                    </select> <br />*@
                                <input id="place-input" class="form-control" type="text" placeholder="Type a location" style="height:50px; font-size:18px;width:715px;">
                                <input type="hidden" name="lat" id="lat" />
                                <input type="hidden" name="lan" id="lan" />
                                <input type="hidden" name="add" id="add" />
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="100%">
                            <table style="width:100%">
                                <tr>
                                    <td>
                                        <div class="form-group">
                                            <label for="datetimepickerCheckIn">Check In</label>
                                            <div style="padding-left:0px;">
                                                <input class="form-control" type="date" name="checkIn" style="height:50px; width:300px; font-size:18px;">
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <label for="datetimepickerCheckOut">Check Out</label>
                                            <div style="padding-left:0px;">
                                                <input class="form-control" type="date" name="checkOut" style="height:50px; width:300px;font-size:18px;">
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="form-group">
                                            <label for="ddlTotalGuest">No of Guest</label>
                                            <select id="ddlTotalGuest" class="form-control" name="ddlTotalGuest" style="height:50px;  font-size:18px;width:300px">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                                <option value="6">6</option>
                                                <option value="7">7</option>
                                                <option value="8">8</option>
                                                <option value="9">9</option>
                                            </select>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <label for="ddlNoOfRooms">No of Rooms</label>
                                            <select id="ddlNoOfRooms" class="form-control" name="ddlNoOfRooms" style="height:50px; width:310px; font-size:18px;width:300px">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" align="right" style="padding-right:110px;">                                        
                                        <button type="submit" class="btn btn-warning" style="width:150px;height:50px;" value="Sabre" name="action:Sabre">Sabre</button>
                                        <button type="submit" class="btn btn-warning" style="width:150px;height:50px;" value="Tourico" name="action:Tourico">Tourico</button>                                      
                                    </td>                                  
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td width="100%">
                            <table style="width:100%"></table>
                        </td>

                    </tr>
                </table>
            </div>
        </section>
    }
}


<script src="http://maps.google.com/maps/api/js?libraries=places"></script>
<script type="text/javascript">
    var input = $('#place-input');
    
    var autocomplete = new google.maps.places.Autocomplete(input[0]);

    autocomplete.addListener('place_changed', function () {
        var place = autocomplete.getPlace();
        console.log(place);
        if (!place.geometry) {
            window.alert("Information not returned by google.");
            return;
        }
        else {
            $('#lat').val(place.geometry.location.lat());
            $('#lan').val(place.geometry.location.lng());
            //$('#add').val(place.formatted_address);
        }
        return false;
    }
);
    $('#place-input').keypress(function (e) {
        if (e.keyCode == 13) {
            return false;
        }
    });
</script>

UI/Views/Home/SearchHotel.cshtml
@model Common.Sabre.Hotels.Search.OTA_HotelAvailRS
@using System.Web.Script.Serialization;

@{
    ViewBag.Title = "Hotel Search Result";
    var counter = 1;
}
<style type="text/css">
    .hotel-map-label {
        color: #29abe2;
        font-weight: bold;
        border-style: solid;
        border-color: #ffffff;
        background-color: #ffffff;
        padding-left: 2px;
        padding-right: 2px;
    }
</style>
<h1>Hotel Search Result</h1>

@if (Model.AvailabilityOptions != null)
{
    JavaScriptSerializer js = new JavaScriptSerializer();
    string jsonResult = js.Serialize(Model);
    ;
    //Include Maps To website
    <div>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.11&sensor=false" type="text/javascript"></script>
        <script src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerwithlabel/src/markerwithlabel.js" type="text/javascript"></script>
        <script type="text/javascript">
            //console.log(@jsonResult);
            var output = @Html.Raw(Json.Encode(@Model));
            console.log(output);
            // check DOM Ready
            $(document).ready(function () {
                // execute
                (function () {
                    // map options
                    var options = {
                        zoom: 10,
                        center: new google.maps.LatLng(@ViewBag.Lat, @ViewBag.Lan),
                        mapTypeId: google.maps.MapTypeId.TERRAIN,
                        mapTypeControl: false
                    };

                    // init map
                    var map = new google.maps.Map(document.getElementById('map_canvas'), options);


                    // set multiple marker
                    $.each(output.AvailabilityOptions, function(index, details){
                        var price ="";
                        if(details.BasicPropertyInfo.RateRange != null && details.BasicPropertyInfo.RateRange.Min != null)
                        {
                            price = details.BasicPropertyInfo.RateRange.CurrencyCode + " $" + details.BasicPropertyInfo.RateRange.Min;
                        }
                        else
                        {
                            price = "N/A";
                        }

                        var markerImage = 'https://maps.google.com/mapfiles/kml/shapes/parking_lot_maps.png';
                        var marker = new MarkerWithLabel({
                            position: new google.maps.LatLng(details.BasicPropertyInfo.Latitude, details.BasicPropertyInfo.Longitude),
                            labelContent: price,
                            icon: markerImage,
                            labelAnchor: new google.maps.Point(-15, 25),
                            labelClass: "hotel-map-label",
                            title: details.BasicPropertyInfo.HotelName,
                            map: map,
                            hotel: details,
                            animation: google.maps.Animation.DROP
                        });

                        google.maps.event.addListener(marker, 'click', function () {
                            //alert("I am " + marker.title + ". Check browser console log for more details.");
                            self.showHotelItemDetails(details);
                        });
                    
                    });                   
                })();
            });


            function showHotelItemDetails(hotel)
            {
                console.log(hotel);
                location.hash = '';
                location.hash = "#" + hotel.BasicPropertyInfo.HotelCode;
            }
        </script>

    </div>
    <div id="map_canvas" style="height:400px;"></div>
    <div style="font-size:12px;">

        @foreach (var details in Model.AvailabilityOptions)
        {
            using (Html.BeginForm("Index", "HotelDetails"))
            {
                <table width="100%" class="rcorners" id="@details.BasicPropertyInfo.HotelCode">
                    <tr>

                        <td colspan="4"></td>
                    </tr>
                    <tr>
                        <td width="5%">&nbsp;</td>
                        <td style="width:20%">
                            @{ var imageName = counter + ".jpg";
                             counter++;
                             if (counter > 4) { counter = 1; }
                            }
                            <img src="~/Images/@imageName" style="width:250px; height:250px;" />
                        </td>
                        <td style="width:55%">
                            <table width="100%">
                                <tr>
                                    <td>
                                        <h3>
                                            @details.BasicPropertyInfo.HotelName
                                        </h3>
                                        Code: @details.BasicPropertyInfo.HotelCode
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @{var hotelAddress = string.Empty;}
                                        @foreach (var address in details.BasicPropertyInfo.Address)
                                        {
                                            hotelAddress += address + " ";
                                        }

                                        <p>@hotelAddress </p>
                                        <p>@details.BasicPropertyInfo.LocationDescription.Text</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @{
                if (@details.BasicPropertyInfo.RateRange != null)
                {
                    <h3>$@details.BasicPropertyInfo.RateRange.Min - $@details.BasicPropertyInfo.RateRange.Max</h3>
                }
                                        }
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @{var specialOffers = string.Empty;}
                                        @{if (details.BasicPropertyInfo.SpecialOffers.Text != null)
                                        {
                                            specialOffers = details.BasicPropertyInfo.SpecialOffers.Text;
                                        }
                                        else
                                        {
                                            specialOffers = "Not available";
                                        }
                                        }
                                        <p> <b>Special Offers:</b> @specialOffers</p>

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p><b>Latitude:</b> @details.BasicPropertyInfo.Latitude</p>
                                        <p><b>Longitude:</b> @details.BasicPropertyInfo.Longitude</p>
                                    </td>
                                </tr>
                            </table>

                        </td>

                        <td style="width:20%">
                            <div style="max-height:300px; overflow:auto">
                                @foreach (var t in details.BasicPropertyInfo.PropertyOptionInfo.GetType().GetProperties())
                                {
                                    var childType = t.GetValue(details.BasicPropertyInfo.PropertyOptionInfo, null);
                                    var val = childType.GetType().GetProperty("Ind").GetValue(childType, null);
                                    <p><b>@t.Name </b> @val</p>
                                    var value = t;
                                }
                            </div>

                        </td>
                    </tr>
                    <tr>
                        <td width="5%">&nbsp;</td>
                        <td colspan="1">
                            <p><b>Phone: </b>@details.BasicPropertyInfo.ContactNumbers.ContactNumber.Phone  <b>Fax: </b>@details.BasicPropertyInfo.ContactNumbers.ContactNumber.Fax</p>
                        </td>
                        <td>
                            <b>Start Date:</b> @ViewBag.StartDate  <b>End Date:</b> @ViewBag.EndDate
                            <input type="hidden" name="startDate" value="@ViewBag.StartDate" />
                            <input type="hidden" name="endDate" value="@ViewBag.EndDate" />
                            <input type="hidden" name="totalTravellers" value="@ViewBag.TotalTravellers" />
                            <input type="hidden" name="hotelCode" value="@details.BasicPropertyInfo.HotelCode" />
                        </td>
                        <td>
                            <button type="submit" class="btn btn-warning" style="width:150px;">Select</button>
                        </td>
                    </tr>
                </table>
            }
        }
    </div>
}
else
{
    <p style="color:red; font-size:15px;">No record found  </p>
}

<style type="text/css">
    .rcorners {
        border-radius: 7px;
        border: 2px solid #73AD21;
    }
</style>